In [3]:
import numpy as np

x=np.random.rand(5)
y=np.random.randn(5)
z=np.random.random(5)
w=np.random.randint(0,5,5)
w=np.random.normal(5)
a=np.random.choice(5)
b=np.random.uniform(5)

print(x)
print(y)
print(z)
print(w)
print(a)
print(b)

print(np.random.randint(0,11,5))

[0.40189929 0.13970448 0.75252064 0.13126907 0.58566001]
[-0.14177314 -0.74446043  0.79224845 -0.08694054 -0.36844011]
[0.47042862 0.57835497 0.14006154 0.26287944 0.64312525]
5.74332735896163
0
2.9770082478801894
[ 1 10  9  0  0]


In [6]:
mat=[1,0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]
print(mat)
t=np.array(mat)
print(t)
t.reshape(5,4)

[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0]


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0]])